id: WATER_WORLD

version: 0.1.0

addons:
  language-yaml: 1.+
  chunk-generator-noise-3d: 1.+
  config-noise-function: 1.+
  palette-block-shortcut: 1.+
  config-biome: 1.+
  config-palette: 1.+
  config-feature: 1.+
  config-distributors: 1.+
  config-locators: 1.+
  config-ore: 1.+
  biome-provider-single: 1.+
  biome-provider-pipeline-v2: 1.+
  generation-stage-feature: 1.+
  structure-block-shortcut: 1.+
  structure-terrascript-loader: 1.+
  terrascript-function-sampler: 1.+
  structure-function-check-noise-3d: 1.+

generator: NOISE_3D

biomes:
  type: PIPELINE
  resolution: 4
  blend:
    amplitude: 2
    sampler:
    type: OPEN_SIMPLEX_2
    frequency: 0.1
  pipeline:
    source:
      type: SAMPLER
      biomes:
        - deeper: 1
        - deep: 20
        - shallow: 32
      sampler:
        dimensions: 2
        type: LINEAR
        min: -1
        max: -0.3
        sampler:
          type: EXPRESSION
          expression: biomePlacement(x,z) + |((originEffect(x,z) - 1)/2)|
          samplers:
            biomePlacement:
              type: DOMAIN_WARP
              dimensions: 2
              sampler:
                type: FBM
                octaves: 3
                lacunarity: 2
                gain: 0.4
                sampler:
                  type: CELLULAR
                  frequency: 0.0008
              amplitude: 2.0
              warp:
                type: OPEN_SIMPLEX_2
                frequency: 0.02
            originEffect: #increase value as you get closer to (0,0)
              dimensions: 2
              type: DISTANCE
              distance-function: Euclidean
              normalize: true
              radius: 100



    stages:
      - type: REPLACE
        sampler:
          type: OPEN_SIMPLEX_2
          frequency: 0.01
        from: shallow
        to:
          - SHALLOWS: 1
      - type: REPLACE
        sampler:
          type: OPEN_SIMPLEX_2
          frequency: 0.01
        from: deep
        to:
          - PLAINS: 1
      - type: REPLACE
        sampler:
          type: OPEN_SIMPLEX_2
          frequency: 0.01
        from: deeper
        to:
          - ABYSSAL_PLAINS: 1


stages:
  - id: preprocessors
    type: FEATURE
  - id: fillTerrain
    type: FEATURE
  - id: ores
    type: FEATURE
  - id: flora
    type: FEATURE
  - id: decor
    type: FEATURE

samplers:
  arches:
    dimensions: 3
    type: FBM
    octaves: 4
    sampler:
      type: OPEN_SIMPLEX_2
      frequency: 0.0075
  simplex3d:
    dimensions: 3
    type: FBM
    octaves: 4
    sampler:
      type: OPEN_SIMPLEX_2
      salt: 484841
      frequency: 0.0075